# Generated by Django 3.2.8 on 2021-10-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userbase_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='postcode',
        ),
        migrations.AlterField(
            model_name='userbase',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
