# Generated by Django 3.2.8 on 2021-10-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-list-alt', help_text='Font Awesome or Bootstrap class [https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free][https://icons.getbootstrap.com/](e.g, fa fa-shopping-cart)', max_length=255),
        ),
    ]
