# Generated by Django 3.2.8 on 2021-10-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-list-alt', help_text='Font Awesome Class[https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free](e.g, fa fa-shopping-cart', max_length=255),
        ),
    ]
