# Generated by Django 3.2.8 on 2021-10-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211013_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa fa-list-alt', help_text='Font Awesome or Bootstrap class [https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free][https://icons.getbootstrap.com/](e.g, fa fa-shopping-cart)', max_length=255),
        ),
    ]
