# Generated by Django 3.2.8 on 2021-10-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='max_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='min_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
