# Generated by Django 3.2.8 on 2021-10-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211014_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='in_stock',
        ),
    ]
