# Generated by Django 3.2.8 on 2021-10-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_service_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='created_by',
            new_name='vendor',
        ),
    ]
