# Generated by Django 3.2.8 on 2021-10-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0005_remove_vendor_business_email'),
        ('store', '0007_auto_20211014_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_product_related', to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
