# Generated by Django 3.2.8 on 2021-10-16 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_auto_20211015_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_servicerequests_related', to='store.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_servicerequests_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
