# Generated by Django 3.2.8 on 2021-10-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='responded_to',
            field=models.BooleanField(default=False),
        ),
    ]
