# Generated by Django 3.2.8 on 2021-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
